#pragma checksum "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "97ae2fe09b86d33fcf6a11faafd861df8f93ef3c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Submit), @"mvc.1.0.view", @"/Views/Home/Submit.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\_ViewImports.cshtml"
using Proj3_Patel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\_ViewImports.cshtml"
using Proj3_Patel.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"97ae2fe09b86d33fcf6a11faafd861df8f93ef3c", @"/Views/Home/Submit.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6ce10ad0c0cd68620d7570b2acbb8fe9935269e5", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Submit : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Proj3_Patel.Models.RegisterViewModel>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n\r\n<h2>Thank you for registering!</h2>\r\n<h4><strong>Name:</strong> ");
#nullable restore
#line 5 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                      Write(Model.Registration.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Address:</strong> ");
#nullable restore
#line 6 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                         Write(Model.Registration.Address);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>City:</strong> ");
#nullable restore
#line 7 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                      Write(Model.Registration.City);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>State:</strong> ");
#nullable restore
#line 8 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                       Write(Model.Registration.State);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Zip:</strong> ");
#nullable restore
#line 9 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                     Write(Model.Registration.Zip);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Gender:</strong> ");
#nullable restore
#line 10 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                        Write(Model.Registration.Gender);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Age:</strong> ");
#nullable restore
#line 11 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                     Write(Model.Registration.Age);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Subscribe: </strong>");
#nullable restore
#line 12 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                           Write(Model.Registration.IsSubscribing);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Degree Program: </strong>");
#nullable restore
#line 13 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                                Write(Model.Registration.Degree);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h4><strong>Favorite University: </strong>");
#nullable restore
#line 14 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                                     Write(Model.Registration.University);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n<h5><strong>Registered on: </strong>");
#nullable restore
#line 15 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                               Write(Model.RegistrationDate.ToShortDateString());

#line default
#line hidden
#nullable disable
            WriteLiteral("</h5>\r\n<h5><strong>Client Info: </strong>");
#nullable restore
#line 16 "C:\Users\RPATE262\Desktop\Proj3-Patel\Views\Home\Submit.cshtml"
                             Write(Model.ClientInfo);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h5>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Proj3_Patel.Models.RegisterViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
